### ISSUE TITLE
aliyunsdkcore.acs_exception.exceptions.ClientException: SDK.InvalidRegionId 

### ISSUE THREAD

**Issue by hantmac** [aliyun/aliyun-openapi-python-sdk#131]
When I use the code as folowing to get my instance info,

```
clt = client(access_key_id_ali, access_key_secret_ali, region)
request = DescribeInstancesRequest.DescribeInstancesRequest()
request.set_accept_format('json')
response = clt.do_action_with_exception(request)
```
 When region = 'cn-hongkong'， I got an error , "aliyunsdkcore.acs_exception.exceptions.ClientException: SDK.InvalidRegionId, Can not find endpoint to access "

But other region such like 'eu-central-1', 'cn-shanghai', 'ap-southeast-1' is ok.

**Comment by hantmac** [comment]
After many tests, I found a law is  this action sometimes successful, sometimes fail, no matter what regionId I put in.

**Comment by Qingtang-SDK** [comment]
The issue you have encountered here is a bug due to bad endpoint design & implementation, in some legacy versions. We are very sorry to any inconvenience. 

Please update your ```aliyun-python-sdk-core``` to the newest version (current ``2.11.0``) and try again. You can update your SDK core via ```pip install aliyun-python-sdk-core==2.11.0```. Please let me know if the problem was not solved.  Thank you.

**Comment by hantmac** [comment]
Thank u for your reply.
    And I wanna to know why this bug sometimes appear, sometimes not appear?
In my opinion, the API about endpoint resolve might have bugs, and other services which need to resolve endpoint might have the same problem.

**Comment by Qingtang-SDK** [comment]
The legacy endpoint management is built on a remote configuration service called "location service", which tells SDK which particular endpoint should be used given Region ID and Product ID. The problem is, this service is not very stable, and SDK has no enough error handling to deal with it. So, you will see ```SDK. InvalidRegionID``` very often, and the frequency of it depends on your network settings.

The newest SDK version uses local static configuration by default, to avoid unstable remote service dependence.

**Comment by hantmac** [comment]
From https://pypi.org/project/aliyun-python-sdk-core/, the newest sdk (aliyun-python-sdk-core==2.11.0) requires: Python <3?
Is there any newest version for python 3 or greater?

**Comment by hantmac** [comment]
This bug depends on the Internet environment, I did't use the newest SDK version because of the python version.
Solved.

**Comment by Qingtang-SDK** [comment]
> From https://pypi.org/project/aliyun-python-sdk-core/, the newest sdk (aliyun-python-sdk-core==2.11.0) requires: Python <3?
> Is there any newest version for python 3 or greater?

Sorry for the late response.

For Python 3.x version, please use ```aliyun-python-sdk-core-v3```, version 2.11.0
It's an issue that users like you have choose different core package for different python version. We are trying to solve it by making ```aliyun-python-sdk-core``` compatible for both Python 2.x and 3.x.

Thank you.
