### ISSUE TITLE
failed to access cn-zhangjiakou with AcsClient using 

### ISSUE THREAD

**Issue by cuericlee** [aliyun/aliyun-openapi-python-sdk#60]
cn-zhangjiakou
list stacks...
/Library/Python/2.7/site-packages/aliyunsdkcore/client.py:309: DeprecationWarning: get_response() method is deprecated, please use do_action_with_exception() instead.
  DeprecationWarning)
Can not find endpoint to access.

aliyun-python-sdk-core (2.6.2)
aliyun-python-sdk-ros (2.2.7)
aliyunsdkcore (1.0.1)

**Comment by gaort** [comment]
@cuericlee 
thanks for your feedback!
This problem is caused by the SDK can not resolve the ROS service endpoint in the cn-zhangjiakou region. 
In this case, you can obtain the endpoint by looking at the [ROS API documents](https://help.aliyun.com/document_detail/28903.html), and then configure the following code

```python
from aliyunsdkcore.profile import region_provider
region_provider.modify_point('ROS', 'cn-zhangjiakou', 'ros.aliyuncs.com')
```

**Comment by cuericlee** [comment]
thanks, it is working for me now.
